[project]
name = "rate_limiter"
version = "0.1.0"
description = "This is a rate-limiter package"
authors = [
    {name = "Vivek"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.124.0,<0.125.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "redis (==5.2.1)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
include-package-data = true
